# Generated by Django 4.2.5 on 2023-10-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0002_remove_cart_user_cart_name_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
