# Generated by Django 4.2.5 on 2023-10-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0004_remove_cart_user_alter_cart_total_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='Carrinho', max_length=200),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
