# Generated by Django 4.2.5 on 2023-10-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0007_remove_cart_name_remove_userprofile_products_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hora_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
