# Generated by Django 4.2.5 on 2023-10-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0008_cart_hora_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='hora_retirada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
