# Generated by Django 4.2.5 on 2023-10-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0008_favoritar'),
        ('app_cantinho', '0009_alter_cart_hora_retirada'),
    ]

    operations = [
    ]
