# Generated by Django 4.2.5 on 2023-10-27 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cantinho', '0010_merge_0008_favoritar_0009_alter_cart_hora_retirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('hora_retirada', models.TimeField(blank=True, null=True)),
                ('status_pagamento', models.CharField(default='pending', max_length=20)),
                ('codigo_pix', models.CharField(blank=True, max_length=20, null=True)),
                ('products', models.ManyToManyField(blank=True, to='app_cantinho.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
