# Generated by Django 4.2.5 on 2023-10-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0012_pedido_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cantinho.cart'),
        ),
    ]
