# Generated by Django 4.2.5 on 2023-10-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0014_remove_pedido_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cantinho.cart'),
        ),
    ]
