# Generated by Django 4.2.5 on 2023-10-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0017_pedido_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cart',
        ),
    ]
