# Generated by Django 4.2.5 on 2023-10-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0019_pedido_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cantinho.cart'),
        ),
    ]
