# Generated by Django 4.2.5 on 2023-10-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0020_alter_pedido_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='hora_retirada',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_cantinho.cart'),
        ),
    ]
