# Generated by Django 4.2.5 on 2023-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
