# Generated by Django 4.2.5 on 2023-11-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0023_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
