# Generated by Django 4.2.5 on 2023-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0024_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
