# Generated by Django 4.2.5 on 2023-11-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0026_remove_review_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='vendinha',
        ),
    ]
