# Generated by Django 4.2.5 on 2023-11-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0028_review_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cantinho.pedido'),
        ),
    ]
