# Generated by Django 4.2.5 on 2023-11-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cantinho', '0024_userprofile_saldo'),
        ('app_cantinho', '0030_alter_review_pedido'),
    ]

    operations = [
    ]
