name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: cantinho-cesar-2  
  PYTHON_VERSION: '3.11'             

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r project_cantinho/requirements.txt

      - name: Install Selenium
        run: pip install selenium

      - name: Run  server e Tests
        run: |
          python project_cantinho/manage.py runserver &
                  sleep 5
          python project_cantinho/manage.py test app_cantinho

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: cantinho-cesar-2  
          publish-profile: |
            <publishData>
              <publishProfile profileName="cantinho-cesar-2 - Web Deploy" publishMethod="MSDeploy" publishUrl="cantinho-cesar-2.scm.azurewebsites.net:443" msdeploySite="cantinho-cesar-2" userName="$cantinho-cesar-2" userPWD="cBCu9QKbhorudJssiSLHLyjFhmLruANJCGqyGzotg0aCo8GuwFpzR65avdDy" destinationAppUrl="https://cantinho-cesar-2.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
                <databases />
            </publishProfile>
