name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: cantinho-cesar-2  
  PYTHON_VERSION: '3.11'             

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r project_cantinho/requirements.txt

      - name: Install Selenium
        run: pip install selenium

      - name: Run  server e Tests
        run: |
          python project_cantinho/manage.py runserver &
                  sleep 5
          python project_cantinho/manage.py test app_cantinho

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/
