name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r project_cantinho/requirements.txt
    - name: Run Tests
      run: |
        python project_cantinho/manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v2
        with:
          name: app_cantinho
          path: project_cantinho\app_cantinho
  
      - name: 'Deploy to azure'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Exquisite-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          environment-url: ${{ secrets.AZURE_CREDENTIALS }}
        
      
